# Generated by Django 5.0.7 on 2024-07-30 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입시간')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('nationality', models.CharField(max_length=255, verbose_name='국적')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=255, unique=True, verbose_name='닉네임')),
            ],
        ),
    ]
