# Generated by Django 5.0.7 on 2024-08-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12341234', max_length=255, verbose_name='비밀번호'),
        ),
    ]
