# Generated by Django 5.0.7 on 2024-08-01 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('dairy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dairy_feedback', models.TextField(verbose_name='왓셩 피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='DairyKeyword',
            fields=[
                ('dairykeyword_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255, verbose_name='감정키워드')),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='dairies.dairy', verbose_name='감정일기')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weather', models.TextField(verbose_name='날씨 질문')),
                ('self_praise', models.TextField(verbose_name='자기 칭찬')),
                ('special_joy', models.TextField(verbose_name='특별 순간')),
                ('highlight', models.TextField(verbose_name='하이라이트')),
                ('dairy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='dairies.dairy')),
            ],
        ),
    ]
