# Generated by Django 5.0.7 on 2024-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairies', '0002_dairy_anger_dairy_fear_dairy_gratitude_dairy_joy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='dairy_feedback',
        ),
        migrations.AddField(
            model_name='question',
            name='dairy_feedback',
            field=models.TextField(default='', verbose_name='왓셩 피드백'),
        ),
    ]
