# Generated by Django 5.0.7 on 2024-08-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairies', '0003_remove_dairy_dairy_feedback_question_dairy_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='bright_color',
            field=models.CharField(default='', max_length=7, verbose_name='명도RGB'),
        ),
        migrations.AddField(
            model_name='dairy',
            name='emotion_color',
            field=models.CharField(default='', max_length=7, verbose_name='색조RGB'),
        ),
    ]
