# Generated by Django 5.0.7 on 2024-08-01 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('monthlyreport_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('month_score', models.IntegerField(verbose_name='행복점수')),
                ('monthly_feedback', models.TextField(verbose_name='한달 ai feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='Hexagonal',
            fields=[
                ('hexagonal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emo1', models.IntegerField()),
                ('emo2', models.IntegerField()),
                ('emo3', models.IntegerField()),
                ('emo4', models.IntegerField()),
                ('emo5', models.IntegerField()),
                ('emo6', models.IntegerField()),
                ('monthly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hexagonal', to='reports.monthlyreport')),
            ],
        ),
        migrations.CreateModel(
            name='HappyGraph',
            fields=[
                ('happygraph_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(verbose_name='행복글 작성시간')),
                ('post_score', models.IntegerField(verbose_name='행복글 행복점수')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happygraphs', to='reports.monthlyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Wordcloud',
            fields=[
                ('wordcloud_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_keyword', models.CharField(max_length=255, verbose_name='행복글 키워드')),
                ('keyword_count', models.IntegerField(verbose_name='키워드 빈도수')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordclouds', to='reports.monthlyreport')),
            ],
        ),
    ]
